### ISSUE TITLE
entity checks condition of one of multiple options

### ISSUE THREAD

**Issue by chienhsingwu** [Kong/kong-plugin#13]
Hi I am adding JWKS support for the JWT plugin so that when the specified algorithm requires a rsa_public_key, I am adding an option to specify jwks_url. Could someone help defining the entity_checks condition for me? Below is the current code:

    entity_checks = {
      { conditional = { if_field = "algorithm",
                        if_match = {
                          match_any = { patterns = { "^RS256$", "^RS384$", "^RS512$" }, },
                        },
                        then_field = "rsa_public_key",
                        then_match = {
                          required = true,
                          custom_validator = validate_ssl_key,
                        },
                      },
      },
    },

Thanks.

**Comment by Tieske** [comment]
what is the behaviour you're getting? also what does the full schema look like, the `entity_checks` can be defined on multiple levels, make sure you do it at the right one.

**Comment by chienhsingwu** [comment]
I plan to add a new field called jwks_url like below and wanted to change the entity check to say either jws_url or rsa_public_key is required, but not both.

`  jwt_secrets = {
    name = "jwt_secrets",
    primary_key = { "id" },
    cache_key = { "key" },
    endpoint_key = "key",
    workspaceable = true,
    admin_api_name = "jwts",
    admin_api_nested_name = "jwt",
    fields = {
      { id = typedefs.uuid },
      { created_at = typedefs.auto_timestamp_s },
      { consumer = { type = "foreign", reference = "consumers", required = true, on_delete = "cascade", }, },
      { key = { type = "string", required = false, unique = true, auto = true }, },
      { secret = { type = "string", auto = true }, },
      { rsa_public_key = { type = "string" }, },
      **{ jwks_url = { type = "string" }, },**
      { algorithm = {
          type    = "string",
          default = "HS256",
          one_of  = {
            "HS256",
            "HS384",
            "HS512",
            "RS256",
            "RS384",
            "RS512",
            "ES256",
            "ES384"
          },
      }, },
      { tags = typedefs.tags },
    },
    entity_checks = {
      { conditional = { if_field = "algorithm",
                        if_match = {
                          match_any = { patterns = { "^RS256$", "^RS384$", "^RS512$" }, },
                        },
                        then_field = "rsa_public_key",
                        then_match = {
                          required = true,
                          custom_validator = validate_ssl_key,
                        },
                      },
      },
    },
  },
`

**Comment by Tieske** [comment]
if you add the same condition, but then make the `then` field `jws_url` and force it to equal `null` or `nil` does that work?

**Comment by chienhsingwu** [comment]
I am not sure what you meant how that additional condition would cover the need to have jws_url defined when rsa_public_key is nil.

Below is what I had. Would this work? I would like to add a condition to prevent both being specified. Any advice of how to do that?

    entity_checks = {
      { conditional_at_least_one_of = { if_field = "algorithm",
        if_match = {
          match_any = { patterns = { "^RS256$", "^RS384$", "^RS512$" }, },
        },
        then_at_least_one_of = {"rsa_public_key", "jwks_url"},
        then_err = "must set one of %s when 'algorith' is 'RS???'"
      }}
    }

**Comment by Tieske** [comment]
typically what I do, is write a unit test that tests the behaviour, and then fiddle with the schema (based on examples of other plugins and Kong itself) until it works the way I want it to.

**Comment by chienhsingwu** [comment]
Thanks. I was wondering where the documentation (either on the web or in the code) of the validation rules are.

**Comment by Tieske** [comment]
they are lacking, most is here: https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/plugin-configuration/ but especially the conditionals are missing there

**Comment by Tieske** [comment]
@chienhsingwu is this resolved, can we close this?

**Comment by chienhsingwu** [comment]
Yes Thanks.
