### ISSUE TITLE
how to  develop multiple plug-ins under a git directory 

### ISSUE THREAD

**Issue by liuyunlong1229** [Kong/kong-plugin#14]
If I want to develop multiple plug-ins under a git directory and integrate them into the k8s environment, what should I do? Is there an example for reference

**Comment by Tieske** [comment]
@liuyunlong1229 this repo template can host multiple plugins if that's what you're asking? the plugins are namespaced ("myplugin"). So just copy the directories and rockspec file.

for installing see the docs, in k8s you can use config maps or alternatively create a custom image (see https://github.com/Kong/docker-kong/tree/master/customize for example)
