### ISSUE TITLE
How to add luamqtt luarocks module in handeler.lua? Actually spend whole day but still not succed.I want to use mqtt protocol with kong

### ISSUE THREAD

**Issue by Kibria7533** [Kong/kong-plugin#36]
local mqtt= require "resty.http"
local con = require "mqtt"

local plugin = {
  PRIORITY = 1000, -- set the plugin priority, which determines plugin execution order
  VERSION = "0.1", -- version in X.Y.Z format. Check hybrid-mode compatibility requirements.
}

function plugin:init_worker()
  -- your custom code here
  kong.log.debug("saying hi from the 'init_worker' handler")

end --]]

-- runs in the 'access_by_lua_block'
function plugin:access(plugin_conf)

  -- your custom code here
  kong.log.debug("llllllllllllllllllllllllllllllll*************************************************************************************************************************************************************")
  kong.log.inspect(mqtt)
   kong.log.debug("qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq")
  kong.log.inspect(plugin_conf)   -- check the logs for a pretty-printed config!
  kong.service.request.set_header(plugin_conf.request_header, "this is on a request")

end

return plugin

**Comment by Tieske** [comment]
Can you explain a bit on what you are tryuing to do? a one-shot post to a topic, or a persistent mqtt session?

The latter is hard, due to the openresty sockets.

**Comment by Kibria7533** [comment]
Hi there,One shot post to a topic is fine for now. Can you help me. How to
achieve this?

Regards
GK

**Comment by Tieske** [comment]
have you tried the examples?

https://github.com/xHasKx/luamqtt/blob/master/examples/openresty/app/main-sync.lua

**Comment by Kibria7533** [comment]
Yes sir,I did. Actually i don't have previous experience with openresty. As
per in the previous link when ever i am trying to add at the top of
handler.lua the line like local mqtt= require "mqtt". Its returning no
module find.

Why you all are shows only simple add or change header from plugin template
in the blog or tutorials?  Will you give me some resources on demo how we
can connect with redis or mosquito server (one shot)?.  Thanks

Regards
Gk.

**Comment by Tieske** [comment]
closing due to being stale.
