### ISSUE TITLE
Testing with strategy off doesn't work

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-plugin#38]
Maybe I'm missing something with the setup, but if the strategy is off, calling `make-yaml_file()` with out any arguments tries to export the database

https://github.com/Kong/kong-plugin/blob/ad362b7235d8d9844a376f557fad003f0138e90e/spec/myplugin/02-integration_spec.lua#L36

and that always throws an error for me 

`'kong config db_export' only works with a database`

**Comment by esatterwhite** [comment]
The only thing I'm doing differently is I'm just hard coding strategy to `off` rather than iterating over `helpers.all_strategies()`

**Comment by esatterwhite** [comment]
does iterating over all_strategies() happen to always run against postgres first, so there is a database setup for `off` to work 😕 ?

**Comment by Tieske** [comment]
see https://github.com/Kong/kong-pongo/issues/303

**Comment by esatterwhite** [comment]
> see [Kong/kong-pongo#303](https://github.com/Kong/kong-pongo/issues/303)

https://github.com/Kong/kong-pongo/issues/303#issuecomment-1202763302

What does "experts and start db less" mean here

**Comment by Tieske** [comment]
should have been "exports", edited that response.

The process is that the test-helpers will write to the DB (for postgress, cassandra, and db-less), and only in case of db-less testing, it will export the contents to a file and start Kong dbless using that file.
