### ISSUE TITLE
Remove reference to mockbin.org

### ISSUE THREAD

**Issue by rspurgeon** [Kong/kong-plugin#39]
This comment references mockbin.org which is now disabled.  It's unclear if the test uses mockbin.org, but the comment should remove it for plugin developers to avoid confusion.  I could not raise a PR due to permissions on the repo.

https://github.com/Kong/kong-plugin/blob/ad362b7235d8d9844a376f557fad003f0138e90e/spec/myplugin/02-integration_spec.lua#L63

**Comment by Tieske** [comment]
good catch, wasn't being used, but has been in there for ages probably
